### ISSUE TITLE
available in reverse?

### ISSUE THREAD

**Issue by Quantlyx** [mpdroog/github_mirror_gitea#1]
I am looking for a way to sync my entire gitea instance (so all repos) to a "mirror" github account.
Maybe you have some tips?
Ty a lot for ur help!

**Comment by mpdroog** [comment]
https://docs.gitea.io/en-us/repo-mirror/#setting-up-a-push-mirror-from-gitea-to-github

**Comment by mpdroog** [comment]
I guess you could look at the browser developer console to see what API-calls get done when doing that manually and then automate that.
